export interface nutrient {
    label: string,
    quantity: number,
    unit: string,
}

export interface sub {
    label: string,
    tag: string,
    schemaOrgTag: string,
    total: number,
    hasRDI: boolean,
    daily: number,
    unit: string,
}


// Edamam Interface
export interface Edamam {
    q: string,
    from: number,
    to: number,
    more: boolean,
    count: number,
    hits: {
        recipe: {
            uri: string,
            label: string,
            image: string,
            source: string,
            url: string,
            shareAs: string,
            yield: number,
            dietLabels: string[],
            healthLabels: string[],
            cautions: string[],
            ingredientLines: string[],
            ingredients: {
                text: string,
                quantity: number,
                measure: string,
                food: string,
                weight: number,
                foodCategory: string,
                foodId: string,
                image: string,
            }[],
            calories: number,
            totalWeight: number,
            totalTime: number,
            cuisineType: string[],
            mealType: string[],
            dishType: string[],
            totalNutrients: {
                ENERC_KCAL: nutrient,
                FAT: nutrient,
                FASAT: nutrient,
                FATRN: nutrient,
                FAMS: nutrient,
                FAPU: nutrient,
                CHOCDF: nutrient,
                "CHOCDF.net": nutrient,
                FIBTG: nutrient,
                SUGAR: nutrient,
                "SUGAR.added": nutrient,
                PROCNT: nutrient,
                CHOLE: nutrient,
                NA: nutrient,
                CA: nutrient,
                MG: nutrient,
                K: nutrient,
                FE: nutrient,
                ZN: nutrient,
                P: nutrient,
                VITA_RAE: nutrient,
                VITC: nutrient,
                THIA: nutrient,
                RIBF: nutrient,
                NIA: nutrient,
                VITB6A: nutrient,
                FOLDFE: nutrient,
                FOLDFD: nutrient,
                FOLAC: nutrient,
                VITB12: nutrient,
                VITD: nutrient,
                TOCPHA: nutrient,
                VITK1: nutrient,
                "Sugar.alcohol": nutrient,
                WATER: nutrient,
            },
            totalDaily: {
                ENERC_KCAL: nutrient,
                FAT: nutrient,
                FASAT: nutrient,
                CHOCDF: nutrient,
                FIBTG: nutrient,
                PROCNT: nutrient,
                CHOLE: nutrient,
                NA: nutrient,
                CA: nutrient,
                MG: nutrient,
                K: nutrient,
                FE: nutrient,
                ZN: nutrient,
                P: nutrient,
                VITA_RAE: nutrient,
                VITC: nutrient,
                THIA: nutrient,
                RIBF: nutrient,
                NIA: nutrient,
                VITB6A: nutrient,
                FOLDFE: nutrient,
                VITB12: nutrient,
                VITD: nutrient,
                TOCPHA: nutrient,
                VITK1: nutrient
            },
            digest: {
                label: string,
                tag: string,
                schemaOrgTag: string,
                total: number,
                hasRDI: boolean,
                daily: number,
                unit: string,
                sub: sub[]
            }[]
        }
    }
}

export interface EdamamV2 {
    from: number,
    to: number,
    count: number,
    _links: {
        next: {
            href: string,
            title: string,
        }
    },
    hits: {
        recipe: {
            uri: string,
            label: string,
            image: string,
            images: {
                THUMBNAIL: {
                    url: string,
                    width: number,
                    height: number,
                },
                SMALL: {
                    url: string,
                    width: number,
                    height: number,
                },
                REGULAR: {
                    url: string,
                    width: number,
                    height: number,
                },
            },
            source: string,
            url: string,
            shareAs: string,
            yield: number,
            dietLabels: string[],
            healthLabels: string[],
            cautions: string[],
            ingredientLines: string[],
            ingredients: {
                text: string,
                quantity: number,
                measure: string,
                food: string,
                weight: number,
                foodCategory: string,
                foodId: string,
                image: string,
            }[],
            calories: number,
            totalCO2Emissions: number,
            co2EmissionsClass: string,
            totalWeight: number,
            totalTime: number,
            cuisineType: string[],
            mealType: string[],
            dishType: string[],
            totalNutrients: {
                ENERC_KCAL: nutrient,
                FAT: nutrient,
                FASAT: nutrient,
                FATRN: nutrient,
                FAMS: nutrient,
                FAPU: nutrient,
                CHOCDF: nutrient,
                "CHOCDF.net": nutrient,
                FIBTG: nutrient,
                SUGAR: nutrient,
                "SUGAR.added": nutrient,
                PROCNT: nutrient,
                CHOLE: nutrient,
                NA: nutrient,
                CA: nutrient,
                MG: nutrient,
                K: nutrient,
                FE: nutrient,
                ZN: nutrient,
                P: nutrient,
                VITA_RAE: nutrient,
                VITC: nutrient,
                THIA: nutrient,
                RIBF: nutrient,
                NIA: nutrient,
                VITB6A: nutrient,
                FOLDFE: nutrient,
                FOLFD: nutrient,
                FOLAC: nutrient,
                VITB12: nutrient,
                VITD: nutrient,
                TOCPHA: nutrient,
                VITK1: nutrient,
                "Sugar.alcohol": nutrient,
                WATER: nutrient,
            },
            totalDaily: {
                ENERC_KCAL: nutrient,
                FAT: nutrient,
                FASAT: nutrient,
                CHOCDF: nutrient,
                FIBTG: nutrient,
                PROCNT: nutrient,
                CHOLE: nutrient,
                NA: nutrient,
                CA: nutrient,
                MG: nutrient,
                K: nutrient,
                FE: nutrient,
                ZN: nutrient,
                P: nutrient,
                VITA_RAE: nutrient,
                VITC: nutrient,
                THIA: nutrient,
                RIBF: nutrient,
                NIA: nutrient,
                VITB6A: nutrient,
                FOLDFE: nutrient,
                VITB12: nutrient,
                VITD: nutrient,
                TOCPHA: nutrient,
                VITK1: nutrient,
            },
            digest: {
                label: string,
                tag: string,
                schemaOrgTag: string,
                total: number,
                hasRDI: boolean,
                daily: number,
                unit: string,
                sub: {
                    label: string,
                    tag: string,
                    schemaOrgTag: string,
                    total: number,
                    hasRDI: boolean,
                    daily: number,
                    unit: string,
                }[]
            }
        },
        _links: {
            self: {
                title: string,
                href: string,
            }
        }
    }[],
}

export interface Query {
    type?: string,
    beta?: boolean,
    q?: string,
    app_id?: string,
    app_key?: string,
    ingr?: string,
    diet?: string[],
    health?: string[],
    cuisineType?: string[],
    mealType?: string[],
    dishType?: string[],
    calories?: string,
    time?: string,
    imageSize?: string[],
    glycemicIndex?: string,
    excluded?: string[],
    random?: boolean,
    nutrients?: {
        CA?: string,
        CHOCDF?: string,
        "CHOCDF.net"?: string,
        CHOLE?: string,
        ENERC_KCAL?: string,
        FAMS?: string,
        FAPU?: string,
        FASAT?: string,
        FAT?: string,
        FATRN?: string,
        FE?: string,
        FIBTG?: string,
        FOLAC?: string,
        FOLDFE?: string,
        FOLDFD?: string,
        K?: string,
        MG?: string,
        NA?: string,
        NIA?: string,
        P?: string,
        PROCNT?: string,
        RIBF?: string,
        SUGAR?: string,
        "SUGAR.added"?: string,
        "Sugar.alcohol"?: string,
        THIA?: string,
        TOCPHA?: string,
        VITA_RAE?: string,
        VITB12?: string,
        VITB6A?: string,
        VITC?: string,
        VITD?: string,
        VITK1?: string,
        WATER?: string,
        ZN?: string,
    },
    field?: string[],
    co2EmissionsClass?: string,
    tag?: string[],
    "Accept-Language"?: string,
}

export interface QueryWithID {
    id?: string,
    type?: string,
    beta?: boolean,
    app_id?: string,
    app_key?: string,
    field?: string[],
    "Accept-Language"?: string,
}

export const DietLabels: string[] = [
    'balanced',
    'high-fiber',
    'high-protein',
    'low-carb',
    'low-fat',
    'low-sodium'
]

export const HealthLabels: string[] = [
    'alcohol-cocktail',
    'alcohol-free',
    'celery-free',
    'crustacean-free',
    'dairy-free',
    'DASH',
    'egg-free',
    'fish-free',
    'fodmap-free',
    'gluten-free',
    'immuno-supportive',
    'keto-friendly',
    'kidney-friendly',
    'kosher',
    'low-potassium',
    'low-sugar',
    'lupine-free',
    'Mediterranean',
    'mollusk-free',
    'mustard-free',
    'No-oil-added',
    'paleo',
    'peanut-free',
    'pecatarian',
    'pork-free',
    'red-meat-free',
    'sesame-free',
    'shellfish-free',
    'soy-free',
    'sugar-conscious',
    'sulfite-free',
    'tree-nut-free',
    'vegan',
    'vegetarian',
    'wheat-free',
]

export const MealTypes: string[] = [
    'breakfast',
    'brunch',
    'lunch',
    'dinner',
    'snack',
    'teatime'
]

export const DishTypes: string[] = [
    'Alcohol%20cocktail',
    'Biscuits%20and%20cookies',
    'Bread',
    'Cereals',
    'Condiments%20and%20sauces',
    'Desserts',
    'Drinks',
    'Egg',
    'Ice%20cream%20and%20custard',
    'Main course',
    'Pancake',
    'Pasta',
    'Pastry',
    'Pies%20and%20tarts',
    'pizza',
    'Preps',
    'Preserve',
    'Salad',
    'Sandwiches',
    'Seafood',
    'Side%20dish',
    'Soup',
    'Special%20occasions',
    'Starter',
    'Sweets'
]

export const CuisineType: string[] = [
    'American',
    'Asian',
    'British',
    'Caribbean',
    'Central%20Europe',
    'Chinese',
    'Eastern%20Europe',
    'French',
    'Greek',
    'Indian',
    'Italian',
    'Japanese',
    'Korean',
    'Kosher',
    'Mediterranean',
    'Mexican',
    'Middle%20Eastern',
    'Nordic',
    'South%20American',
    'South%20East%20Asian',
    'World'
]